version: '3.3'

services:
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    entrypoint: ./docker/app/entrypoint.sh
    ports:
      - '8020:8020'
    depends_on:
      - kafka
    tmpfs:
      - /tmp
    volumes:
      - .:/app/code

  faust-worker1:
    build:
      dockerfile: ./docker/app/Dockerfile
      context: .
    ports:
      - '6066:6066'
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka
    entrypoint: ./docker/worker/entrypoint.sh

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
